const { ipcRenderer } = require('electron');
const fs = require('fs');
const path = require('path');

function getIconDataUrl(name) {
  try {
    const iconPath = path.join(__dirname, '../../../assets/icons', `${name}.png`);
    if (fs.existsSync(iconPath)) return `data:image/png;base64,${fs.readFileSync(iconPath).toString('base64')}`;
  } catch (error) {}
  return '';
}

function setupTopBar() {
  const icons = Object.fromEntries(['shuffle', 'previous', 'rewind', 'play', 'pause', 'fast-forward', 'next', 'repeat', 'like', 'volume', 'mute', 'avatar', 'exit'].map(name => [name.replace('-', ''), getIconDataUrl(name)]));
  const bar = document.createElement('div');
  bar.id = 'ytm-custom-topbar';
  bar.innerHTML = `<div class="topbar-container"><div class="topbar-controls"><button class="topbar-btn" id="btn-shuffle" title="Aleatório"><img src="${icons.shuffle}" alt="Aleatório"></button><button class="topbar-btn" id="btn-previous" title="Música Anterior"><img src="${icons.previous}" alt="Anterior"></button><button class="topbar-btn" id="btn-rewind" title="Voltar 10s"><img src="${icons.rewind}" alt="Voltar 10s"></button><button class="topbar-btn play-btn" id="btn-play-pause" title="Play / Pause"><img id="img-play-pause" src="${icons.play}" alt="Play/Pause"></button><button class="topbar-btn" id="btn-fastforward" title="Avançar 10s"><img src="${icons.fastforward}" alt="Avançar 10s"></button><button class="topbar-btn" id="btn-next" title="Próxima Música"><img src="${icons.next}" alt="Próxima"></button><button class="topbar-btn" id="btn-repeat" title="Repetir"><img src="${icons.repeat}" alt="Repetir"></button><button class="topbar-btn" id="btn-like" title="Curtir"><img src="${icons.like}" alt="Curtir"></button><button class="topbar-btn" id="btn-mute" title="Volume / Mudo"><img id="img-mute" src="${icons.volume}" alt="Volume"></button></div><div class="topbar-actions"><button class="topbar-btn user-btn" id="btn-user-switch" title="Mudar de Conta"><img src="${icons.avatar}" alt="Usuário"><span id="active-user-name" class="user-label">Contas</span></button><button class="topbar-btn exit-btn" id="btn-app-exit" title="Fechar Aplicativo"><img src="${icons.exit}" alt="Fechar"></button></div></div><div id="ytm-account-modal" class="account-modal hidden"><div class="modal-header"><h3>Alternar Conta</h3><span class="modal-close" id="btn-close-modal">&times;</span></div><div id="accounts-list" class="accounts-list"></div><div class="modal-footer"><button id="btn-add-account" class="btn-add-account">Adicionar Nova Conta</button></div></div>`;
  const style = document.createElement('style');
  style.textContent = `#ytm-custom-topbar{position:fixed;top:0;left:0;right:0;height:48px;background:rgba(18,18,18,.92);backdrop-filter:blur(12px);border-bottom:1px solid rgba(255,255,255,.08);z-index:999999;display:flex;align-items:center;padding:0 16px;box-sizing:border-box;-webkit-app-region:drag}.topbar-container{width:100%;display:flex;align-items:center;justify-content:space-between;gap:12px}.topbar-controls,.topbar-actions{display:flex;align-items:center;gap:8px;-webkit-app-region:no-drag}.topbar-btn{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:8px;width:34px;height:34px;display:flex;align-items:center;justify-content:center;cursor:pointer;padding:0}.topbar-btn img{width:16px;height:16px;object-fit:contain;pointer-events:none}.topbar-btn:hover{background:rgba(255,255,255,.15)}.play-btn{background:rgba(255,0,0,.2)}.user-btn{width:auto;padding:0 12px;gap:8px}.user-label{color:#fff;font-size:12px;max-width:120px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.exit-btn{background:rgba(255,59,48,.15)}.exit-btn:hover{background:#ff3b30}.account-modal{position:absolute;top:54px;right:16px;width:300px;background:#1e1e1e;border:1px solid rgba(255,255,255,.12);border-radius:12px;padding:16px;color:#fff;z-index:1000000;-webkit-app-region:no-drag}.account-modal.hidden{display:none}.modal-header{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid rgba(255,255,255,.08);padding-bottom:10px;margin-bottom:12px}.modal-header h3{font-size:14px;margin:0}.modal-close{cursor:pointer;font-size:20px;color:#888}.accounts-list{display:flex;flex-direction:column;gap:8px;max-height:200px;overflow-y:auto;margin-bottom:14px}.account-item{display:flex;align-items:center;justify-content:space-between;padding:10px 12px;border-radius:8px;background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.06);cursor:pointer}.account-item.active{background:rgba(255,0,0,.15);border-color:rgba(255,0,0,.5)}.account-info{display:flex;flex-direction:column;gap:2px;overflow:hidden}.account-name{font-size:13px;color:#fff}.account-email{font-size:11px;color:#888}.active-badge{font-size:11px;color:#ff4444;font-weight:600}.btn-add-account{width:100%;padding:10px;background:#f00;color:#fff;border:0;border-radius:8px;cursor:pointer} `;
  document.head.appendChild(style);
  document.body.prepend(bar);
  const action = (id, fn) => document.getElementById(id).addEventListener('click', fn);
  action('btn-play-pause', () => { const button = document.querySelector('#play-pause-button,.play-pause-button'); if (button) button.click(); else { const video = document.querySelector('video'); if (video) video.paused ? video.play() : video.pause(); } });
  action('btn-next', () => document.querySelector('.next-button,tp-yt-paper-icon-button.next-button')?.click());
  action('btn-previous', () => document.querySelector('.previous-button,tp-yt-paper-icon-button.previous-button')?.click());
  action('btn-rewind', () => { const video = document.querySelector('video'); if (video) video.currentTime = Math.max(0, video.currentTime - 10); });
  action('btn-fastforward', () => { const video = document.querySelector('video'); if (video) video.currentTime = Math.min(video.duration || Infinity, video.currentTime + 10); });
  action('btn-shuffle', () => document.querySelector('ytmusic-player-bar .shuffle,.ytmusic-player-bar.shuffle,tp-yt-paper-icon-button.shuffle')?.click());
  action('btn-repeat', () => document.querySelector('ytmusic-player-bar .repeat,.ytmusic-player-bar.repeat,tp-yt-paper-icon-button.repeat')?.click());
  action('btn-like', () => document.querySelector('ytmusic-player-bar ytmusic-like-button-renderer #button[aria-label*="Gostei"],ytmusic-player-bar ytmusic-like-button-renderer tp-yt-paper-icon-button.like')?.click());
  action('btn-mute', () => { const video = document.querySelector('video'); if (video) { video.muted = !video.muted; document.getElementById('img-mute').src = video.muted ? icons.mute : icons.volume; } });
  action('btn-app-exit', () => ipcRenderer.send('app-exit'));
  const modal = document.getElementById('ytm-account-modal');
  const renderAccounts = async () => { const { accounts, activeAccountId } = await ipcRenderer.invoke('get-accounts'); document.getElementById('accounts-list').innerHTML = accounts.map(acc => `<div class="account-item ${acc.id === activeAccountId ? 'active' : ''}" data-id="${acc.id}"><div class="account-info"><span class="account-name">${acc.name}</span>${acc.email ? `<span class="account-email">${acc.email}</span>` : ''}</div>${acc.id === activeAccountId ? '<span class="active-badge">Ativa</span>' : ''}</div>`).join(''); document.querySelectorAll('.account-item').forEach(item => item.onclick = async () => { if (item.dataset.id !== activeAccountId) await ipcRenderer.invoke('switch-account', item.dataset.id); modal.classList.add('hidden'); }); document.getElementById('active-user-name').textContent = accounts.find(acc => acc.id === activeAccountId)?.name || 'Contas'; };
  action('btn-user-switch', () => { modal.classList.toggle('hidden'); if (!modal.classList.contains('hidden')) renderAccounts(); });
  action('btn-close-modal', () => modal.classList.add('hidden'));
  action('btn-add-account', async () => { const name = prompt('Nome da nova conta:', 'Conta 2'); if (name) await ipcRenderer.invoke('add-account', name); });
  renderAccounts();
}
module.exports = { setupTopBar };
